[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino

monitor_speed = 115200
upload_protocol = esptool
upload_port = /dev/cu.usbmodem3101
monitor_port = /dev/cu.usbmodem3101

board_build.flash_mode = dio
board_build.f_flash = 40000000L

lib_deps = bodmer/TFT_eSPI @ ^2.5.43

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MOSI=4
    -D TFT_SCLK=2
    -D TFT_CS=10
    -D TFT_DC=1
    -D TFT_RST=0
    -D TFT_BL=-1
    -D TFT_BACKLIGHT_ON=HIGH
    -D TFT_MISO=-1
    -D SPI_FREQUENCY=40000000
    -D TFT_RGB_ORDER=TFT_BGR
