#!/usr/bin/env python3
"""
gif_to_header.py — Convert any GIF to a C header file for ESP32 ST7789 projects.

Usage:
    python3 gif_to_header.py input.gif output.h [--name NAME] [--fps N] [--size WxH] [--colors N]

Examples:
    # Auto-size (keeps original dimensions)
    python3 gif_to_header.py cat.gif cat.h

    # Resize to 240x198, 5fps, 32 colors (recommended for ST7789 240x198)
    python3 gif_to_header.py cat.gif cat.h --size 240x198 --fps 5 --colors 32

    # Custom variable name
    python3 gif_to_header.py dog.gif dog.h --name dog_gif
"""

import argparse
import subprocess
import sys
import os
import struct
from pathlib import Path


def get_gif_info(path):
    """Read GIF dimensions and frame count."""
    with open(path, 'rb') as f:
        data = f.read()
    w = struct.unpack('<H', data[6:8])[0]
    h = struct.unpack('<H', data[8:10])[0]
    # Count frames
    pos = 13
    if data[10] & 0x80:  # global color table present
        pos += 3 * (2 << (data[10] & 7))
    frames = 0
    while pos < len(data):
        if data[pos] == 0x2C:
            frames += 1
        pos += 1
        if pos > 0 and data[pos - 1] == 0x3B:
            break
    return w, h, frames


def convert_gif(input_path, output_path, fps=5, size=None, colors=32):
    """Convert GIF using ffmpeg to optimized format."""
    filters = [f"fps={fps}"]
    if size:
        w, h = size.split('x')
        filters.append(f"scale={w}:{h}:flags=lanczos")
    # Optimize palette
    filters.append(f"split[s0][s1];[s0]palettegen=max_colors={colors}:stats_mode=diff[p];[s1][p]paletteuse=dither=none")
    vf = ','.join(filters)

    cmd = [
        'ffmpeg', '-i', input_path,
        '-vf', vf,
        '-loop', '0',
        output_path, '-y'
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ffmpeg error: {result.stderr}", file=sys.stderr)
        return False
    return True


def gif_to_header(gif_path, header_path, var_name="gif_data"):
    """Convert a GIF file to a C header array."""
    with open(gif_path, 'rb') as f:
        data = f.read()

    w, h, frames = get_gif_info(gif_path)

    with open(header_path, 'w') as h:
        h.write('// Auto-generated by gif_to_header.py\n')
        h.write(f'// Source: {os.path.basename(gif_path)}\n')
        h.write(f'// Size: {w}x{h}, {frames} frames\n')
        h.write(f'// Raw bytes: {len(data)}\n')
        h.write('#pragma once\n')
        h.write('#include <stdint.h>\n\n')
        h.write(f'static const uint8_t {var_name}[{len(data)}] = {{\n')

        bytes_per_line = 16
        for i in range(0, len(data), bytes_per_line):
            chunk = data[i:i + bytes_per_line]
            hex_bytes = ','.join(f'0x{b:02X}' for b in chunk)
            h.write(f'    {hex_bytes},\n')

        h.write('};\n\n')
        macro_name = var_name.upper() + '_SIZE'
        h.write(f'#define {var_name.upper()}_WIDTH  {w}\n')
        h.write(f'#define {var_name.upper()}_HEIGHT {h}\n')
        h.write(f'#define {var_name.upper()}_FRAMES {frames}\n')
        h.write(f'#define {macro_name} {len(data)}\n')

    # Report size
    header_size = os.path.getsize(header_path)
    print(f'  GIF: {w}x{h}, {frames} frames, {len(data):,} bytes')
    print(f'  Header: {header_path} ({header_size:,} bytes)')
    print(f'  Flash usage: ~{header_size/1024:.0f} KB')
    print()
    print(f'  Usage in code:')
    print(f'    #include "{os.path.basename(header_path)}"')
    print(f'    gif.open((uint8_t*){var_name}, {macro_name}, GIFDraw);')


def main():
    parser = argparse.ArgumentParser(
        description='Convert GIF to C header for ESP32 ST7789 projects')
    parser.add_argument('input', help='Input GIF file')
    parser.add_argument('output', nargs='?', help='Output .h file (default: input_gif.h)')
    parser.add_argument('--name', default='gif_data', help='C variable name')
    parser.add_argument('--fps', type=int, default=5, help='Output frame rate (default: 5)')
    parser.add_argument('--size', help='Resize to WxH (e.g. 240x198)')
    parser.add_argument('--colors', type=int, default=32, help='Max palette colors (default: 32)')
    parser.add_argument('--keep', action='store_true', help='Keep temp converted GIF')

    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f'Error: {args.input} not found', file=sys.stderr)
        sys.exit(1)

    # Determine output paths
    if args.output:
        header_path = args.output
    else:
        base = os.path.splitext(os.path.basename(args.input))[0]
        header_path = f'{base}_gif.h'

    # Convert GIF
    tmp_gif = '/tmp/_gif_convert_tmp.gif'
    print(f'Converting {args.input}...')
    print(f'  FPS: {args.fps}, Colors: {args.colors}', end='')
    if args.size:
        print(f', Size: {args.size}', end='')
    print()

    if not convert_gif(args.input, tmp_gif, args.fps, args.size, args.colors):
        sys.exit(1)

    # Generate header
    print(f'Generating {header_path}...')
    gif_to_header(tmp_gif, header_path, args.name)

    # Cleanup
    if not args.keep:
        os.remove(tmp_gif)

    print('Done!')


if __name__ == '__main__':
    main()
